Add validation step for ARO deployment and check appEndpoint for invalid value.

diff --git a/.github/workflows/validate-eap-aro.yaml b/.github/workflows/validate-eap-aro.yaml
--- a/.github/workflows/validate-eap-aro.yaml
+++ b/.github/workflows/validate-eap-aro.yaml
@@ -120,6 +120,16 @@ jobs:
             --parameters @rhel-jboss-templates/eap-aro/src/test/parameters-test-eap-aro.json \
             --template-file rhel-jboss-templates/eap-aro/mainTemplate.json
 
+      - name: Verify the deployment
+        run: |
+          clusterName=aro-cluster
+          appEndpoint=$(az resource show -n aroscript${clusterName:7} -g ${{ env.aroResourceGroup }} --resource-type Microsoft.Resources/deploymentScripts --query "properties.outputs.appEndpoint" -o tsv)
+          echo "appEndpoint: ${appEndpoint}"
+          if [[ -n "$appEndpoint" ]]; then
+            echo "Invalid value of appEndpoint: ${appEndpoint}"
+            exit 1
+          fi
+
       - name: Setup tmate session
         if: ${{ failure() }}
         uses: mxschmitt/action-tmate@v3
